/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_henryrenyz_creflect_ReflectLibImpl */

#ifndef _Included_com_henryrenyz_creflect_ReflectLibImpl
#define _Included_com_henryrenyz_creflect_ReflectLibImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    callMethodObject0
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_callMethodObject0
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    callMethodInt0
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_callMethodInt0
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    callMethodShort0
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)S
 */
JNIEXPORT jshort JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_callMethodShort0
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    callMethodByte0
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)B
 */
JNIEXPORT jbyte JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_callMethodByte0
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    callMethodLong0
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_callMethodLong0
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    callMethodFloat0
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)F
 */
JNIEXPORT jfloat JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_callMethodFloat0
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    callMethodDouble0
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)D
 */
JNIEXPORT jdouble JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_callMethodDouble0
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    callMethodBoolean0
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_callMethodBoolean0
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    callMethodChar0
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)C
 */
JNIEXPORT jchar JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_callMethodChar0
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    callMethodVoid0
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_callMethodVoid0
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    getFieldObject0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_getFieldObject0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    getFieldInt0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_getFieldInt0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    getFieldShort0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;)S
 */
JNIEXPORT jshort JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_getFieldShort0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    getFieldByte0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;)B
 */
JNIEXPORT jbyte JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_getFieldByte0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    getFieldLong0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_getFieldLong0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    getFieldFloat0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;)F
 */
JNIEXPORT jfloat JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_getFieldFloat0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    getFieldDouble0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;)D
 */
JNIEXPORT jdouble JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_getFieldDouble0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    getFieldBoolean0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_getFieldBoolean0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    getFieldChar0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;)C
 */
JNIEXPORT jchar JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_getFieldChar0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    setFieldObject0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_setFieldObject0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    setFieldInt0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_setFieldInt0
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    setFieldShort0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;S)V
 */
JNIEXPORT void JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_setFieldShort0
  (JNIEnv *, jclass, jobject, jobject, jshort);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    setFieldByte0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;B)V
 */
JNIEXPORT void JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_setFieldByte0
  (JNIEnv *, jclass, jobject, jobject, jbyte);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    setFieldLong0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;J)V
 */
JNIEXPORT void JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_setFieldLong0
  (JNIEnv *, jclass, jobject, jobject, jlong);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    setFieldFloat0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;F)V
 */
JNIEXPORT void JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_setFieldFloat0
  (JNIEnv *, jclass, jobject, jobject, jfloat);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    setFieldDouble0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;D)V
 */
JNIEXPORT void JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_setFieldDouble0
  (JNIEnv *, jclass, jobject, jobject, jdouble);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    setFieldBoolean0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;Z)V
 */
JNIEXPORT void JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_setFieldBoolean0
  (JNIEnv *, jclass, jobject, jobject, jboolean);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    setFieldChar0
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;C)V
 */
JNIEXPORT void JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_setFieldChar0
  (JNIEnv *, jclass, jobject, jobject, jchar);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    newInstance0
 * Signature: (Ljava/lang/reflect/Constructor;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_newInstance0
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    allocInstance0
 * Signature: (Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_allocInstance0
  (JNIEnv *, jclass, jclass);

/*
 * Class:     com_henryrenyz_creflect_ReflectLibImpl
 * Method:    refUtilInit0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_henryrenyz_creflect_ReflectLibImpl_refUtilInit0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
